name: chanmovie
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  carousel_slider: ^5.0.0
  fluttertoast: ^8.1.2
  font_awesome_flutter: ^10.3.0
  http: ^1.1.2
  image_cropper: ^8.0.2
  image_picker: ^1.0.5
  path_provider: ^2.0.11
  shared_preferences: ^2.1.2
  sqflite: ^2.2.2
  url_launcher: ^6.1.7
  webview_flutter: ^4.4.2
  youtube_player_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/icon.png
    - asset/user.png
